### ISSUE TITLE
It's not working.

### ISSUE THREAD

**Issue by dheroying** [mitipi/serverless-ngrok-tunnel#8]
I've followed the guide in the ReadMe file.
But it shows the error and not working.
I am not sure what is wrong.
![screenshot_42](https://user-images.githubusercontent.com/54707202/135849053-14c97149-a727-4d93-aaa1-fc596389b221.png)

**Comment by IlizarragaEtan** [comment]
I've the same problem, did you solve it?
I've this configuration

- serverless.yml
```
custom:
  ngrokTunnel:
    ngrokOptions:
      - region: 'us'
      - authtoken: ${env:NGROK_AUTH_TOKEN}
    tunnels:
      - port: 3000
plugins:
  - serverless-offline
  - serverless-ngrok-tunnel
  - serverless-webpack
  - serverless-plugin-include-dependencies
  - serverless-dotenv-plugin
  - serverless-sentry
```

- command to run 
```
serverless offline start --host 0.0.0.0 --stage dev --prefix dev --tunnel=true
```

- console
```
Serverless: Offline [HTTP] listening on http://0.0.0.0:3000
Serverless: Enter "rp" to replay the last request
Serverless: Tunnels error: ngrok is not yet ready to start tunnels. Trying to reconnect in 5 seconds...
Serverless: Tunnels error: ngrok is not yet ready to start tunnels. Trying to reconnect in 5 seconds...
Serverless: Unable to create tunnel: ngrok is not yet ready to start tunnels
Serverless: Closing tunnels...
Serverless: Closing tunnels...
```
